version: '3.8'

services:
  app:
    build:
      context: ./docker/php/
      dockerfile: ./Dockerfile
    container_name: sso-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/sso
      - vendor:/var/www/sso/vendor
    working_dir: /var/www/sso
    command: sh /var/www/sso/start.sh
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - network_1

  db:
    image: mysql:8.0
    container_name: sso-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sso_db
      MYSQL_PASSWORD: password
      MYSQL_USER: sso_user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network_1

  redis:
    image: redis:alpine
    container_name: sso-redis
    ports:
      - "6379:6379"
    networks:
      - network_1
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: sso-rabbitmq
    hostname: sso-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network_1

  websocket:
    build:
      context: ./docker/socket/
      dockerfile: ./Dockerfile
    container_name: websockets
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      - network_1

#  nginx:
#   image: nginx:alpine
#   container_name: ws-proxy
#   ports:
#     - "443:443"
#     - "80:80"
#   volumes:
#     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#     - ./docker/nginx/certs:/etc/nginx/certs
#   depends_on:
#     - websocket
#   restart: unless-stopped

volumes:
  db_data:
  vendor:
  rabbitmq_data:

networks:
  network_1:
    driver: bridge
