version: '3.8'

services:
  app:
    build: ./
    container_name: sso-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/sso
      - vendor:/var/www/sso/vendor
    working_dir: /var/www/sso
    command: sh /var/www/sso/start.sh
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - sso-network

  db:
    image: mysql:8.0
    container_name: sso-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sso_db
      MYSQL_PASSWORD: password
      MYSQL_USER: sso_user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sso-network

  redis:
    image: redis:alpine
    container_name: sso-redis
    ports:
      - "6379:6379"
    networks:
      - sso-network

#  nats:
#    image: nats:latest
#    container_name: sso-nats
#    ports:
#      - "4222:4222"
#      - "6222:6222"
#      - "8222:8222"
#    command: ["-js"]
#    volumes:
#      - nats_data:/opt/nats/data
#    networks:
#      - sso-network

  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: sso-rabbitmq
    hostname: sso-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sso-network

volumes:
  db_data:
  vendor:
  rabbitmq_data:
#  nats_data:

networks:
  sso-network:
    driver: bridge
